//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicaWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Tipo { get; set; }
        public int Nota { get; set; }
        public bool Visto1 { get; set; }
        public bool Visto2 { get; set; }
        public Nullable<System.DateTime> Registrado { get; set; }
        public Nullable<System.DateTime> VistoEm { get; set; }
    }
}
